apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codeready-operator
rules:
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - get
  - create
  - delete
  - update
  - list
  - watch